name: Deploying Continuously to EC2

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd .
          docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd  

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd
            sudo docker kill url-shortener-ci-cd || true
            sudo docker rm url-shortener-ci-cd || true
            sudo docker run -d --name url-shortener-ci-cd -p 4000:4000 ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd
