name: Deploying Continuously to EC2

on:
  push:
    branches:
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd .
          docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener-ci-cd  

      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host:  ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd /home/ubuntu/url-shortener
      #       git pull origin main
      #       npm install
      #       npm run build
      #       pm2 restart all
